pluginManagement {
    repositories {
        if (DEPENDENCY_TYPE == 'mavenLocal') {
            mavenLocal()
        }
        google()
        mavenCentral()
        gradlePluginPortal()
        if (DEPENDENCY_TYPE == 'jitpack') {
            maven { url 'https://jitpack.io' }
        }
    }

}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        if (DEPENDENCY_TYPE == 'mavenLocal') {
            mavenLocal()
        }
        google()
        mavenCentral()
        if (DEPENDENCY_TYPE == 'jitpack') {
            maven { url 'https://jitpack.io' }
        }
    }
}

if (DEPENDENCY_TYPE == 'project') {
    includeBuild 'xlog-libcat-plugin'
}

include ':xlog', ':xlog-libcat', ':xlog-sample'
