apply plugin: 'com.android.application'
apply plugin: 'com.github.lmk26.xlog.libcat'

android {
    namespace 'com.elvishew.xlogsample'
    compileSdkVersion 37

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_21
        targetCompatibility JavaVersion.VERSION_21
    }

    defaultConfig {
        applicationId "com.elvishew.xlogsample"
        minSdkVersion 23
        targetSdkVersion 37
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    buildFeatures {
        buildConfig true
    }
}

dependencies {
    testImplementation 'junit:junit:4.13.2'
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'com.google.android.material:material:1.14.0'
    implementation 'androidx.appcompat:appcompat:1.8.0'
    if (DEPENDENCY_TYPE == 'project') {
        implementation project(':xlog')
        implementation project(':xlog-libcat')
    } else {
        implementation "${GROUP}:xlog:${VERSION}"
        implementation "${GROUP}:xlog-libcat:${VERSION}"
    }
}
